version: '2'
services:
  goldenrealestate-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/GoldenRealEstate/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=GoldenRealEstate
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
